version: '3'
services: 
    db:
        image: postgres:12-alpine
        volumes: 
            - ./_db_init:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        environment:
          POSTGRES_USER: myomer
          POSTGRES_PASSWORD: myomer
          POSTGRES_DB: myomer

    adminer:
        image: adminer
        ports:
            - 8080:8080