version: '3'
services: 
    db:
        image: postgres:12-alpine
        volumes: 
            - ./_db_init:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        env_file: local-docker.env
        
    adminer:
        image: adminer
        ports:
            - 8080:8080
        env_file: local-docker.env
        