version: '3.2'
services: 
    db:
        image: postgres:12-alpine
        volumes: 
            - ./_db_init:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        env_file: ./.env
        
    adminer:
        image: adminer
        ports:
            - 8080:8080
        env_file: ./.env
        
    main:
        build:
            context: .
            dockerfile: ./hmr.dockerfile
        volumes: 
            - ./main.go:/app/main.go
            - ./elements:/app/elements/
            - ./handlers:/app/handlers/
            - ./managers:/app/managers
        ports:
            - 3000:3000
        depends_on: 
            - db
        env_file: ./.env
